### ISSUE TITLE
Arch problem when launching the app

### ISSUE THREAD

**Issue by mboisvertdupras** [egoist/chatkit-desktop#2]
Starting from v3, I have a problem when launching the app. It seems like there's an arm64 package requirement even on the Intel build.

```sh
Uncaught Exception:
Error: dlopen(/Applications/ChatKit.app/Contents/Resources/app.asar.unpacked/node_modules/@egoist/electron-panel-window/build/Release/NativeExtension.node, 0x0001): tried: '/Applications/ChatKit.app/Contents/Resources/app.asar.unpacked/node_modules/@egoist/electron-panel-window/build/Release/NativeExtension.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/ChatKit.app/Contents/Resources/app.asar.unpacked/node_modules/@egoist/electron-panel-window/build/Release/NativeExtension.node' (no such file), '/Applications/ChatKit.app/Contents/Resources/app.asar.unpacked/node_modules/@egoist/electron-panel-window/build/Release/NativeExtension.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))
at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
at Module._extensions..node (node:internal/modules/cjs/loader:1356:18)
at Object.func [as .node] (node:electron/js2c/node_init:2:2441)
at Module.load (node:internal/modules/cjs/loader:1126:32)
at Module._load (node:internal/modules/cjs/loader:967:12)
at c._load (node:electron/js2c/node_init:2:13672)
at Module.require (node:internal/modules/cjs/loader:1150:19)
at require (node:internal/modules/cjs/helpers:119:18)
at bindings (/Applications/ChatKit.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
at Object.<anonymous> (/Applications/ChatKit.app/Contents/Resources/app.asar/node_modules/@egoist/electron-panel-window/index.js:3:24)
```

**Comment by egoist** [comment]
should be fixed in 0.3.6
